Removing undefined properties and merging whole objects
lettercrap/lettercrap pull request #11
Opened 2024-03-18 09:54 UTC by DaveKeehl

Closes #10

2024-03-20 13:20 UTC, dabico requested changes

2024-03-21 07:06 UTC, DaveKeehl commented on src/lettercrap.ts
> +let config: Config = {
Yeah that would work (pretty sure also in TS). Regarding the validations, we could create a function and call inside the forEach.

2024-03-21 11:14 UTC, dabico commented on src/lettercrap.ts
> +let config: Config = {
Yeah, that will be sufficient IMO. The only thing we should take care of is the validation for values like `font_family` and `font_weight`. I think we may have to introduce or re-use some special types that are appropriate for those style settings, as they can't be any string.

2024-03-21 16:14 UTC, dabico commented on src/lettercrap.ts
> +let config: Config = {
For the other values:

- `content` can be any string value, so long as it's not `null` or `undefined`;
- `letters` should be a non-blank string of _printable_ characters;
- `words` can be any array of strings, so long as it's not `null` or `undefined`;
- `update_interval` should be a positive integer.

What do you think?

2024-03-21 16:41 UTC, DaveKeehl commented on src/lettercrap.ts
> +let config: Config = {
> For the other values:
> 
> * `content` can be any string value, so long as it's not `null` or `undefined`;
> * `letters` should be a non-blank string of _printable_ characters;
> * `words` can be any array of strings, so long as it's not `null` or `undefined`;
> * `update_interval` should be a positive integer.
> 
> What do you think?

Sounds good. Some validations will have to be done at runtime though (e.g. check for positive integers, check for non-blank printable characters). We can either do it by hand or by bringing in a validation library like [Zod](https://zod.dev/), which is pretty popular.

2024-03-21 16:44 UTC, DaveKeehl commented on src/lettercrap.ts
> +let config: Config = {
> We should base it on the MDN documentation:
> 
> * https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
> * https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
> 
> In the case of `font_family`, we should probably restrict ourselves to the generic font families, and in the case of `font_weight` the named values (`normal`, `bold`, `bolder` and `lighter`) will suffice.

For font weight I agree it should be enough. However, I'm a bit hesitant regarding font family. I think the user should be free to use any font.

2024-03-24 16:36 UTC, dabico approved these changes

2024-03-24 16:37 UTC, dabico approved these changes

2024-03-24 16:37 UTC, merged